### ISSUE TITLE
document handling packages that are not installed

### ISSUE THREAD

**Issue by basnijholt** [jupyter-widgets/jupyter-sphinx#26]
running `make html` from the `repo/docs` doesn't result in `jupyter_sphinx.execute` using the code from `repo`.

This is a problem in Adaptive, whereas a bad workaround we [install master in the CI.](https://github.com/python-adaptive/adaptive/blob/master/docs/environment.yml#L20)

**Comment by akhmerov** [comment]
One easy and correct way to handle this is to set `PYTHONPATH` from the sphinx's `conf.py`.

**Comment by jbweston** [comment]
> One easy and correct way to handle this is to set PYTHONPATH from the sphinx's conf.py.

This is not enough, unfortunately. `jupyter-execute` launches a separate ipython kernel: no user code is executed in the Python interpreter that is running sphinx. The way I have got around this so far is to have a `boilerplate.py` file that I include with

```
.. jupyter-execute:: boilerplate.py
    :hide-code:
```

but this is kind of unsatisfactory because then the downloadable scripts have the contents of `boilerplate.py` in them. Perhaps we should allow some common code to be executed in a cell prior to any of the cells defined in a given document, and have this cell stripped before writing any output.

**Comment by akhmerov** [comment]
The jupyter kernels inherit the environment from the parent process. This is used with jupyter-sphinx for example [here](https://gitlab.kwant-project.org/kwant/tkwant/blob/master/doc/Makefile#L10-13)
