### ISSUE TITLE
Make the embedder url configurable

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/jupyter-sphinx#4]
This would be useful to have a local use of the extension that use another URL for the javascript.

As per conversation in #3 .

**Comment by michaelpacer** [comment]
If this is going to be configurable here, we probably should also make it configurable in nbconvert, yes?

**Comment by SylvainCorlay** [comment]
Sorry I did not respond to this. +1 on making it configurable globally.

**Comment by infinity0** [comment]
Could we please think about this sort of thing (being able to use local copies rather than downloading everything) *before* release? For jupyter in general I mean, not just this project. Otherwise it makes packaging this for Debian more painful. And it is already incredibly painful due to all this NPM crap.

**Comment by maartenbreddels** [comment]
https://github.com/jupyter-widgets/jupyter-sphinx/pull/16 makes this configurable actually, so merging that could close this issue.

**Comment by jasongrout** [comment]
Closed by #16.
